blank_issues_enabled: false
contact_links:
  - name: Ask a question
    about: Please ask questions and discuss ideas in our GitHub Discussions
    url: https://github.com/cvs-health/askRITA/discussions
